name: test-push-1

on:
# 2020-05-16: disabled
#  push:
#    branches: [ gh-workflow-commit ]
  push:
    branches: [ workflows-okay ]

jobs:
  job_1:
    name: Edit and push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Edit the file
      run: |
        date > wf/date.txt
    - name: Commit and push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Auto: Test auto-commit"
        file_pattern: wf/date.txt

