name: test-event-cron

on:
# 2020-05-16: disabled
#  schedule:
#    - cron:  '35 12 * * *'
#    - cron:  '35 01 * * *'
  push:
    branches: [ workflows-okay ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Notify
      run: echo "Hello, world!"
