name: test-event-cron

on:
  schedule:
    - cron:  '35 12 * * *'
    - cron:  '35 01 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Notify
      run: echo "Hello, world!"
