name: test-fail

#on: [push, pull_request]
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      do_fail:
        description: 'Override env'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DO_FAIL: 'true'
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Override env true if specified
      if: ${{ github.event.inputs.do_fail == 'true' }}
      run: |
        echo "DO_FAIL=true" >> $GITHUB_ENV

    - name: Override env false if specified
      if: ${{ github.event.inputs.do_fail == 'false' }}
      run: |
        echo "DO_FAIL=false" >> $GITHUB_ENV

    - name: Show a success result
      if: ${{ env.DO_FAIL == 'false' }}
      run: |
        echo "DO_FAIL=${{ env.DO_FAIL }}"
        exit 0

    - name: Show a failure result
      if: ${{ env.DO_FAIL == 'true' }}
      run: |
        echo "DO_FAIL=${{ env.DO_FAIL }}"
        exit 1

