name: test-jq-detect-change.yml

# Detect a change to a specific path

on:
# 2021-01-23: disabled
  push:
#    branches: [ initial-gh-workflow ]
    branches: [ workflows-okay ]
    paths:
      - 'wf/repos.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract repo names
      uses: awesome-global-contributions/action-yq@v1.0.2
      with:
        file: wf/src/extract-repo-names.sh
