name: test-linuxbrew

on:
# 2022-07-22:
  push:
    branches: [ initial-gh-workflow ]
#  push:
#    branches: [ workflows-okay ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install a homebrew package
      run: brew install jd

    - name: Show PATH
      run: echo "PATH=$PATH"

    - name: Show which jd
      run: which jd
