name: test-awscli-2

on:
  push:
    branches: [ initial-gh-workflow ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: keithweaver/aws-s3-github-action@master
      with:
        command: ls
        source: api
        destination: s3://foliodocs/

