name: test-jq-yq

on:
# 2020-05-12: disabled
#  push:
#    branches: [ initial-gh-workflow ]
  push:
    branches: [ workflows-okay ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract repo names
      uses: awesome-global-contributions/action-yq@v1.0.2
      with:
        file: wf/src/extract-repo-names.sh
