name: test-python-pip

on:
# 2020-05-16: disabled
#  push:
#    branches: [ initial-gh-workflow ]
  push:
    branches: [ workflows-okay ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        echo "Report python version:"
        python -V
        python -m pip install --upgrade pip
        pip install -r wf/src/requirements.txt

    - name: Run example
      run: python wf/src/hello-pip.py -l debug
