name: test-pr-comment

env:
  MESSAGE: 'example message'
  DO_MESSAGE: false

on: [push, pull_request]

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.REF }}
          submodules: recursive
      - name: Report some info
        if: ${{ env.DO_MESSAGE == 'true' }}
        run: |
          echo "MESSAGE=${{ env.MESSAGE }}"
      - name: Add comment to PR if necessary
        uses: thollander/actions-comment-pull-request@v2
        if: ${{ env.DO_MESSAGE == 'true' }}
        with:
          message: "There: ${{ env.DO_MESSAGE }}"

