name: test-push-1

on:
  push:
    branches: [ gh-workflow-commit ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Edit the file
      run: |
        date > wf/date.txt
        git status
