name: test-push-1

on:
  push:
    branches: [ gh-workflow-commit ]

jobs:
  edit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Edit the file
      run: |
        date > wf/date.txt

  commit:
    name: Commit and push
    needs: edit
    runs-on: ubuntu-latest
    steps:
    - name: 
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Test auto-commit
        file_pattern: wf/date.txt

