name: test-jq-yq

on:
  push:
    branches: [ initial-gh-workflow ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Report python version
      run: python wf/src/hello.py
