name: test-linuxbrew

on:
  push:
    branches: [ initial-gh-workflow ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set linuxbrew path
      run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

    - name: Show PATH
      run: echo "PATH=$PATH"

    - name: Install a homebrew package
      run: brew install jd

    - name: Show PATH
      run: echo "PATH=$PATH"

    - name: Show which jd
      run: which jd
