name: test-install-go

on:
  push:
    branches: [ initial-gh-workflow ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3

    - name: Show Go version
      run: go version

    - name: Install jd
      run: go install github.com/josephburnett/jd@latest

    - name: Show jd version
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        jd --version
